[build]
builder = "NIXPACKS"

[env]
PYTHON_VERSION = "3.11"

[python]
command = "pip install -r requirements.txt"
start = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn config.wsgi"
