# Generated by Django 5.0.1 on 2025-07-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppidBaznasKaltim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pimpinan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pimpinan/')),
                ('deskripsi', models.TextField()),
            ],
        ),
    ]
